// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxukywihurcvuvfbcjmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4dWt5d2lodXJjdnV2ZmJjam1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0Mzg1OTMsImV4cCI6MjA2NzAxNDU5M30.fwYDE9M9P6qAM5QndkjtLjT94vGmOedxwtB-VaUFiV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});